/*
 * requestIntoDialog.java
 *
 * Created on May 14, 2005, 10:05 PM
 */

package digitallibrary;

/**
 *
 * @author  brad
 */
public class aboutDialog extends javax.swing.JDialog {
            
    public aboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        aboutPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        aboutPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aboutPanel.setBackground(new java.awt.Color(97, 143, 169));
        aboutPanel.setBorder(new javax.swing.border.EtchedBorder());
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digitallibrary/images/jculogo_big.png")));
        aboutPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 30, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Digital Library v1.0");
        aboutPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Author : Bradley Jenkins (bradley.jenkins@unix.net)");
        aboutPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Advisor: Dr. Ickjai Lee (Ickjai.Lee@jcu.edu.au)");
        aboutPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jTextArea1.setBackground(new java.awt.Color(97, 143, 169));
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 12));
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(3);
        jTextArea1.setText("Digital Library was produced as a final year project spanning CP3046 and CP3047 2005 at James Cook University by Bradley Jenkins under the guidance  of Dr. Ickjai Lee.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setFocusable(false);
        aboutPanel.add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 380, 60));

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        aboutPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        getContentPane().add(aboutPanel, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-474)/2, (screenSize.height-425)/2, 474, 425);
    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aboutDialog(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    
}
