/*
 * requestIntoDialog.java
 *
 * Created on May 14, 2005, 10:05 PM
 */

package digitallibrary;

/**
 *
 * @author  brad
 */
public class confirmDialog extends javax.swing.JDialog {
            boolean Var;
    //            Variables Var = new Variables();
            static String question = new String();
            
            /** Creates new form requestIntoDialog */
    public confirmDialog(java.awt.Frame parent, boolean modal, String Question) {
        super(parent, modal);
        question = Question;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        Request = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Request.setLayout(new java.awt.GridLayout(1, 1));

        Request.setBorder(new javax.swing.border.EtchedBorder());
        jPanel2.setLayout(new java.awt.GridLayout(3, 3));

        jLabel1.setFont(new java.awt.Font("MS Sans Serif", 0, 16));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Question");
        jLabel1.setMaximumSize(null);
        jPanel2.add(jLabel1);

        jLabel1.setText(question);
        jButton1.setText("Continue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dialog_submit(evt);
            }
        });

        jPanel8.add(jButton1);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel8.add(jButton2);

        jPanel2.add(jPanel8);

        Request.add(jPanel2);

        getContentPane().add(Request, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-474)/2, (screenSize.height-148)/2, 474, 148);
    }//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Var = false;
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Dialog_submit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dialog_submit
        Var = true;
        this.dispose();
    }//GEN-LAST:event_Dialog_submit
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new confirmDialog(new javax.swing.JFrame(), true, question).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Request;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
    
}
