/*
 * popupExceptionDialog2.java
 *
 * Created on May 16, 2005, 1:26 AM
 */

package digitallibrary;

/**
 *
 * @author  brad
 */
public class fileChooser extends javax.swing.JDialog {
    String[] Var; // = new String();
    String[] Var2; // = new String();
    String msg;
    java.io.File[] tmpFileArray;
    String tmpFile;
    
    /** Creates new form popupExceptionDialog2 */
    public fileChooser(java.awt.Frame parent, boolean modal, boolean multi) {
       super(parent, modal);
       //try {
       //         javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
       //         javax.swing.SwingUtilities.updateComponentTreeUI(this);
       //}catch(Exception e){ /* Not windows? fine :) */}
                
       //super();
        initComponents();
        if (multi) {
            jFileChooser1.setMultiSelectionEnabled(true);
        }else{
            jFileChooser1.setMultiSelectionEnabled(false);
            jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        }
        int retVal = jFileChooser1.showOpenDialog(parent);
        if(retVal == javax.swing.JFileChooser.APPROVE_OPTION) {
            if (multi) {
                tmpFileArray = jFileChooser1.getSelectedFiles();//   ().getAbsolutePath();
                this.Var = new String[tmpFileArray.length];
                this.Var2 = new String[tmpFileArray.length];
                for (int i=0; i<tmpFileArray.length; i++) {
                    this.Var[i] = tmpFileArray[i].getAbsolutePath();
                    this.Var2[i] = tmpFileArray[i].getName();
                }
            }else{
                tmpFile = new String(jFileChooser1.getSelectedFile().getAbsolutePath());
            }

        }else {
            this.Var = new String[1];
            this.Var[0] = "";
        }
     }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jFileChooser1 = new javax.swing.JFileChooser();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Error");
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-582)/2, (screenSize.height-385)/2, 582, 385);
    }//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
    
}
