/*
 * requestIntoDialog.java
 *
 * Created on May 14, 2005, 10:05 PM
 */

package digitallibrary;

/**
 *
 * @author  brad
 */
public class requestInfoDialog extends javax.swing.JDialog {
            boolean Var;
            static String question = new String();
            static String dialog = new String();
            
            /** Creates new form requestIntoDialog */
    public requestInfoDialog(java.awt.Frame parent, boolean modal, String Question) {
        super(parent, modal);
        question = Question;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        Request = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Request.setLayout(new java.awt.GridLayout(3, 3));

        Request.setBorder(new javax.swing.border.EtchedBorder());
        Request.add(jPanel6);

        Request.add(jPanel5);

        Request.add(jPanel4);

        Request.add(jPanel3);

        jPanel2.setLayout(new java.awt.GridLayout(3, 3));

        jLabel1.setFont(new java.awt.Font("MS Sans Serif", 0, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Question");
        jPanel2.add(jLabel1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPanel2.add(jTextField1);

        jLabel1.setText(question);
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dialog_submit(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dialogSubmitKey(evt);
            }
        });

        jPanel8.add(jButton1);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogCancel(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dialogCancelKey(evt);
            }
        });

        jPanel8.add(jButton2);

        jPanel2.add(jPanel8);

        Request.add(jPanel2);

        Request.add(jPanel7);

        Request.add(jPanel9);

        getContentPane().add(Request, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-600)/2, (screenSize.height-400)/2, 600, 400);
    }//GEN-END:initComponents

    private void dialogCancelKey(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dialogCancelKey
        Var = false;
        this.dispose();
    }//GEN-LAST:event_dialogCancelKey

    private void dialogSubmitKey(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dialogSubmitKey
        Var = true;
        dialog = jTextField1.getText();
       this.dispose();
    }//GEN-LAST:event_dialogSubmitKey

    private void dialogCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialogCancel
        Var = false;
        this.dispose();
    }//GEN-LAST:event_dialogCancel

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
//        jButton1.requestFocus();
        Dialog_submit(evt);

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void Dialog_submit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dialog_submit
        Var = true;
        dialog = jTextField1.getText();
       this.dispose();        
    }//GEN-LAST:event_Dialog_submit
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new requestInfoDialog(new javax.swing.JFrame(), true, question).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Request;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
